File Name,Domain Name, Private_IP_Found_In_Default_DNS,Private_IP_Found_In_Public_DNS,Default DNS IP's found in Public DNS, Domain Doesn't Work but IP Does,Response Code,Default DNS IP Address,Public DNS Response Codes,All Domain Response Codes,All Default DNS Response Codes,All Public DNS Response Codes,ISP DNS Response Contradiction Public DNS Response between results,Method
Raw_Data_malicious_sites.csv,https://frizonline.com,FALSE,FALSE,TRUE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://financereports.co,FALSE,FALSE,TRUE,FALSE,200,['403'],['403'],['200'],['403'],['403'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://tryteens.com,FALSE,FALSE,TRUE,FALSE,200,"['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']","['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']",['200'],"['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']","['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']","['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://ffupdate.org,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='ffupdate.org'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0537F940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')),"['""HTTPConnectionPool(host=\'errno11001getaddrinfofailed\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x0537FD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\'))""']",[''],"[""HTTPSConnectionPool(host='ffupdate.org'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0537F940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))""]","['""HTTPConnectionPool(host=\'errno11001getaddrinfofailed\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x0537FD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\'))""']",[''],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://subtitleseeker.com,FALSE,FALSE,TRUE,FALSE,200,"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']","['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']",['200'],"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']","['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']","['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://fantasticfilms.ru,FALSE,FALSE,TRUE,TRUE,403,['200'],['200'],['403'],['200'],['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://gardensrestaurantandcatering.com,FALSE,FALSE,TRUE,FALSE,200,['404'],['404'],['200'],['404'],['404'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://hdvideoforums.com,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='hdvideoforums.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04B1C820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond')),['404'],['404'],"[""HTTPSConnectionPool(host='hdvideoforums.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04B1C820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond'))""]",['404'],['404'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://sportsmanclub.net,FALSE,FALSE,TRUE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://stock888.cn,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='stock888.cn'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)'))),"['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']",[''],"[""HTTPSConnectionPool(host='stock888.cn'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)')))""]","['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']",[''],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://teamclouds.com,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='teamclouds.com'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)'))),"['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']","['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']","[""HTTPSConnectionPool(host='teamclouds.com'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)')))""]","['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']","['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']","['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://wadefamilytree.org,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='wadefamilytree.org'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)'))),"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']",['200'],"[""HTTPSConnectionPool(host='wadefamilytree.org'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)')))""]","['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']",['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://iranact.co,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='iranact.co'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)'))),"['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']",['200'],"[""HTTPSConnectionPool(host='iranact.co'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1; '[SSL] unknown error (_ssl.c:1108)')))""]","['""(\'Connection aborted.\'; ConnectionResetError(10054; \'An existing connection was forcibly closed by the remote host\'; None; 10054; None))""']",['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://creativebookmark.com,FALSE,FALSE,TRUE,FALSE,HTTPSConnectionPool(host='creativebookmark.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04B1CB38>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond')),['404'],['404'],"[""HTTPSConnectionPool(host='creativebookmark.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04B1CB38>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond'))""]",['404'],['404'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://vegweb.com,FALSE,FALSE,TRUE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://delgets.com,FALSE,FALSE,TRUE,FALSE,200,['404'],['404'],['200'],['404'],['404'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://totalpad.com,FALSE,FALSE,TRUE,FALSE,HTTPSConnectionPool(host='totalpad.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05463388>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond')),"['""HTTPConnectionPool(host=\'184.168.221.4\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x05463430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond\'))""']","['""HTTPConnectionPool(host=\'184.168.221.4\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x008D7070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond\'))""', '""HTTPConnectionPool(host=\'184.168.221.4\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x008D7BC8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond\'))""']","[""HTTPSConnectionPool(host='totalpad.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05463388>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond'))""]","['""HTTPConnectionPool(host=\'184.168.221.4\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x05463430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond\'))""']","['""HTTPConnectionPool(host=\'184.168.221.4\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x008D7070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond\'))""', '""HTTPConnectionPool(host=\'184.168.221.4\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x008D7BC8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time; or established connection failed because connected host has failed to respond\'))""']","['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://kvfan.net,FALSE,FALSE,TRUE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://hgk.biz,FALSE,FALSE,TRUE,FALSE,403,['403'],['403'],['403'],['403'],['403'],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://youngthroats.com,FALSE,FALSE,TRUE,FALSE,200,"['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']","['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']",['200'],"['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']","['""HTTPSConnectionPool(host=\'136.144.145.155\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)\')))""']","['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",IP Blocking
Raw_Data_malicious_sites.csv,https://metro-ads.co.in,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='metro-ads.co.in'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x01245B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')),"['""HTTPConnectionPool(host=\'errno11001getaddrinfofailed\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x01245508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\'))""']",[''],"[""HTTPSConnectionPool(host='metro-ads.co.in'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x01245B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))""]","['""HTTPConnectionPool(host=\'errno11001getaddrinfofailed\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x01245508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\'))""']",[''],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
Raw_Data_malicious_sites.csv,https://salescript.info,FALSE,FALSE,FALSE,FALSE,HTTPSConnectionPool(host='salescript.info'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00B55448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')),"['""HTTPConnectionPool(host=\'errno11001getaddrinfofailed\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x00B55A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\'))""']",[''],"[""HTTPSConnectionPool(host='salescript.info'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00B55448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))""]","['""HTTPConnectionPool(host=\'errno11001getaddrinfofailed\'; port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x00B55A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed\'))""']",[''],"['False', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'False', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'Block N/A', 'False', 'False', 'Block N/A', 'False', 'False', 'False', 'Block N/A', 'Block N/A']",Domain Not Live
